import React from 'react';
import { useCashDrawerReconciliation } from '../../services/queries';

export interface ZReportModalProps {
  shiftId: number;
  onClose: () => void;
  settings: any;
  fmt: (v: number) => string;
}

export const ZReportModal: React.FC<ZReportModalProps> = ({ shiftId, onClose, settings, fmt }) => {
  const { data: reconciliation, isLoading } = useCashDrawerReconciliation(shiftId);

  if (!shiftId) return null;

  return (
    <div className="fixed inset-0 bg-black/60 z-[100] flex items-center justify-center p-4 print:bg-white print:p-0">
      <div className="bg-white rounded-xl shadow-2xl w-full max-w-sm flex flex-col max-h-[90vh] print:shadow-none print:max-w-none print:m-0 print:p-0">

        <div className="p-4 border-b flex justify-between items-center bg-gray-50 rounded-t-xl print:hidden">
          <h2 className="text-lg font-bold text-gray-900">End of Day (Z-Report)</h2>
          <button onClick={onClose} className="text-gray-500 hover:text-red-500 transition-colors">
            <svg className="w-6 h-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" /></svg>
          </button>
        </div>

        <div className="p-6 overflow-y-auto bg-white text-gray-900 font-mono text-sm print:overflow-visible print:h-auto print:w-full print:block">
          {isLoading ? (
            <div className="flex justify-center items-center py-10">Loading Z-Report...</div>
          ) : reconciliation ? (
            <div className="space-y-4">
              <div className="text-center mb-6 border-b-2 border-dashed border-gray-300 pb-4">
                <h1 className="text-xl font-bold uppercase">{settings?.storeName || 'POS System'}</h1>
                <p className="text-xs mt-1 font-semibold tracking-widest">Z-REPORT</p>
                <p className="text-xs mt-2 text-gray-500">Printed: {new Date().toLocaleString()}</p>
                <p className="text-xs text-gray-500">Shift ID: #{shiftId}</p>
              </div>

              <div className="space-y-1 text-sm">
                <div className="flex justify-between"><span>Transactions:</span><span>{reconciliation.sales}</span></div>
                <div className="flex justify-between font-bold text-base mt-2 pt-2 border-t border-dashed">
                  <span>Gross Sales:</span><span>{fmt(reconciliation.totalSales)}</span>
                </div>
              </div>

              <div className="border-t border-dashed border-gray-300 pt-3 space-y-1 mt-3">
                <p className="font-bold mb-1 uppercase text-xs text-gray-500">Tender Breakdown</p>
                <div className="flex justify-between"><span>Cash Sales:</span><span>{fmt(reconciliation.paymentBreakdown.cash || 0)}</span></div>
                <div className="flex justify-between"><span>Card Sales:</span><span>{fmt(reconciliation.paymentBreakdown.card || 0)}</span></div>
                <div className="flex justify-between"><span>Mobile/Other:</span><span>{fmt(reconciliation.paymentBreakdown.mobile || 0)}</span></div>
              </div>

              <div className="border-t border-dashed border-gray-300 pt-3 space-y-1 mt-3 bg-gray-50 p-2 rounded">
                <p className="font-bold mb-2 uppercase text-xs text-gray-500">Register Status</p>
                <div className="flex justify-between"><span>Opening Balance:</span><span>{fmt(reconciliation.expectedCashBalance - (reconciliation.paymentBreakdown.cash || 0))}</span></div>
                <div className="flex justify-between text-green-700"><span>+ Cash Sales:</span><span>{fmt(reconciliation.paymentBreakdown.cash || 0)}</span></div>
                <div className="flex justify-between font-bold mt-2 pt-2 border-t">
                  <span>Expected Drawer:</span><span>{fmt(reconciliation.expectedCashBalance)}</span>
                </div>
              </div>

              <div className="border-t-2 border-solid border-gray-900 pt-4 text-center text-xs mt-6 text-gray-400">
                <p>Generated by {settings?.storeName || 'POS System'}</p>
                <p>Thank you!</p>
              </div>
            </div>
          ) : (
            <div className="text-center text-red-500 py-10">Could not load Z-Report data.</div>
          )}
        </div>

        <div className="p-4 border-t bg-gray-50 flex gap-3 justify-end rounded-b-xl print:hidden">
          <button onClick={onClose} className="px-4 py-2 border border-gray-300 rounded-lg text-sm font-medium hover:bg-gray-100">Cancel</button>
          <button onClick={() => window.print()} className="px-4 py-2 bg-blue-600 text-white rounded-lg text-sm font-medium hover:bg-blue-700 flex items-center gap-2">
            <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17 17h2a2 2 0 002-2v-4a2 2 0 00-2-2H5a2 2 0 00-2 2v4a2 2 0 002 2h2m2 4h6a2 2 0 002-2v-4a2 2 0 00-2-2H9a2 2 0 00-2 2v4a2 2 0 002 2zm8-12V5a2 2 0 00-2-2H9a2 2 0 00-2 2v4h10z" /></svg>
            Print Receipt
          </button>
        </div>

      </div>
    </div>
  );
};
