import React, { useState } from "react";
import { formatDate } from "../utils/reportUtils";
import { useSettings } from "../context/SettingsContext";
import { formatCurrency } from "../utils/currencyUtils";
import {
  useDailySalesReport,
  useSalesRangeReport,
  useEmployeePerformanceReport,
  useProductPerformanceReport,
  useInventoryReport,
} from "../services/queries";
import {
  BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer,
  Cell, PieChart, Pie, Legend, AreaChart, Area,
} from "recharts";

// ─── Types ────────────────────────────────────────────────────────────────────
type Tab = "overview" | "products" | "employees" | "inventory";

const TABS: { id: Tab; label: string; icon: React.ReactNode }[] = [
  {
    id: "overview", label: "Sales Overview",
    icon: <svg className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z" /></svg>,
  },
  {
    id: "products", label: "Products",
    icon: <svg className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M20 7l-8-4-8 4m16 0l-8 4m8-4v10l-8 4m0-10L4 7m8 4v10M4 7v10l8 4" /></svg>,
  },
  {
    id: "employees", label: "Employees",
    icon: <svg className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0z" /></svg>,
  },
  {
    id: "inventory", label: "Inventory",
    icon: <svg className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 8h14M5 8a2 2 0 110-4h14a2 2 0 110 4M5 8v10a2 2 0 002 2h10a2 2 0 002-2V8m-9 4h4" /></svg>,
  },
];

const PALETTE = ["#6366f1","#10b981","#f59e0b","#ef4444","#8b5cf6","#ec4899","#14b8a6","#f97316","#06b6d4","#84cc16"];

// ─── Print helper ─────────────────────────────────────────────────────────────
const printTable = (title: string, subtitle: string, headings: string[], rows: (string | number)[][]) => {
  const w = window.open("", "_blank");
  if (!w) return;
  const trs = rows.map(r =>
    `<tr>${r.map((c, i) => `<td style="padding:8px 14px;border-bottom:1px solid #f1f5f9;${i > 0 ? "text-align:right" : ""}">${c}</td>`).join("")}</tr>`
  ).join("");
  w.document.write(`<html><head><title>${title}</title><style>
    *{box-sizing:border-box;margin:0;padding:0}
    body{font-family:'Segoe UI',system-ui,sans-serif;padding:40px;color:#0f172a;background:#fff}
    .header{border-bottom:3px solid #6366f1;padding-bottom:20px;margin-bottom:30px}
    h1{font-size:24px;font-weight:800;color:#1e1b4b;margin-bottom:6px}
    .sub{font-size:13px;color:#64748b}
    table{width:100%;border-collapse:collapse;font-size:13px;margin-top:10px}
    thead tr{background:linear-gradient(to right,#6366f1,#8b5cf6);color:#fff}
    th{padding:12px 14px;font-weight:700;text-align:left}
    th:not(:first-child){text-align:right}
    tbody tr:nth-child(even){background:#f8fafc}
    td{color:#334155}
    .footer{margin-top:30px;font-size:11px;color:#94a3b8;text-align:center}
    @media print{body{padding:20px}.footer{display:none}}
  </style></head><body>
    <div class="header"><h1>${title}</h1><div class="sub">${subtitle}</div></div>
    <table>
      <thead><tr>${headings.map((h, i) => `<th${i > 0 ? ' style="text-align:right"' : ''}>${h}</th>`).join("")}</tr></thead>
      <tbody>${trs}</tbody>
    </table>
    <div class="footer">Generated by POS System • ${new Date().toLocaleString()}</div>
    <script>window.onload=()=>{window.print();window.close()}<\/script>
  </body></html>`);
  w.document.close();
};

// ─── Stat Card ────────────────────────────────────────────────────────────────
interface StatCardProps {
  label: string;
  value: string | number;
  sub?: string;
  gradient: string;
  icon: React.ReactNode;
  trend?: { value: number; isPositive: boolean };
}

const StatCard: React.FC<StatCardProps> = ({ label, value, sub, gradient, icon, trend }) => (
  <div className={`relative overflow-hidden rounded-2xl p-5 text-white shadow-md ${gradient}`}>
    <div className="pointer-events-none absolute -right-4 -top-4 h-20 w-20 rounded-full bg-white/10 blur-2xl" />
    <div className="pointer-events-none absolute -bottom-6 -left-4 h-24 w-24 rounded-full bg-black/10 blur-2xl" />
    <div className="relative">
      <div className="mb-3 flex items-center justify-between">
        <div className="flex h-9 w-9 items-center justify-center rounded-xl bg-white/20 backdrop-blur-sm">
          {icon}
        </div>
        {trend && (
          <span className={`rounded-full px-2 py-0.5 text-xs font-bold ${trend.isPositive ? "bg-emerald-400/20 text-emerald-100" : "bg-rose-400/20 text-rose-100"}`}>
            {trend.isPositive ? "↑" : "↓"} {Math.abs(trend.value)}%
          </span>
        )}
      </div>
      <p className="text-xs font-semibold uppercase tracking-wider text-white/70">{label}</p>
      <p className="mt-1 text-2xl font-extrabold leading-tight">{value}</p>
      {sub && <p className="mt-0.5 text-xs text-white/60">{sub}</p>}
    </div>
  </div>
);

// ─── Section Header ───────────────────────────────────────────────────────────
const SectionHeader: React.FC<{ title: string; sub?: string; onPrint?: () => void }> = ({ title, sub, onPrint }) => (
  <div className="flex items-center justify-between">
    <div>
      <h3 className="text-base font-bold text-gray-900">{title}</h3>
      {sub && <p className="mt-0.5 text-xs text-gray-400">{sub}</p>}
    </div>
    {onPrint && (
      <button
        onClick={onPrint}
        className="flex items-center gap-1.5 rounded-lg border border-gray-200 bg-white px-3 py-1.5 text-xs font-semibold text-gray-600 shadow-sm transition-all hover:border-indigo-300 hover:bg-indigo-50 hover:text-indigo-700"
      >
        <svg className="h-3.5 w-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17 17h2a2 2 0 002-2v-4a2 2 0 00-2-2H5a2 2 0 00-2 2v4a2 2 0 002 2h2m2 4h6a2 2 0 002-2v-4a2 2 0 00-2-2H9a2 2 0 00-2 2v4a2 2 0 002 2zm8-12V5a2 2 0 00-2-2H9a2 2 0 00-2 2v4h10z" />
        </svg>
        Print
      </button>
    )}
  </div>
);

// ─── Card wrapper ─────────────────────────────────────────────────────────────
const Card: React.FC<{ children: React.ReactNode; className?: string }> = ({ children, className = "" }) => (
  <div className={`rounded-2xl border border-gray-100 bg-white shadow-sm ${className}`}>{children}</div>
);

// ─── Custom Tooltip ───────────────────────────────────────────────────────────
const ChartTooltip = ({ active, payload, label, formatter }: any) => {
  if (!active || !payload?.length) return null;
  return (
    <div className="rounded-xl border border-gray-100 bg-white/95 p-3 shadow-xl backdrop-blur-sm">
      <p className="mb-1.5 text-xs font-bold text-gray-500">{label}</p>
      {payload.map((p: any, i: number) => (
        <p key={i} className="text-sm font-bold" style={{ color: p.color }}>
          {p.name}: {formatter ? formatter(p.value) : p.value}
        </p>
      ))}
    </div>
  );
};

// ─── Loading Skeleton ─────────────────────────────────────────────────────────
const Skeleton: React.FC = () => (
  <div className="space-y-6 animate-pulse">
    <div className="grid grid-cols-2 gap-4 sm:grid-cols-4">
      {[...Array(4)].map((_, i) => <div key={i} className="h-28 rounded-2xl bg-gradient-to-br from-gray-200 to-gray-100" />)}
    </div>
    <div className="h-64 rounded-2xl bg-gray-100" />
    <div className="h-72 rounded-2xl bg-gray-100" />
  </div>
);

// ─── Badge ────────────────────────────────────────────────────────────────────
const Badge: React.FC<{ color: "green" | "red" | "amber" | "gray"; children: React.ReactNode }> = ({ color, children }) => {
  const styles = {
    green: "bg-emerald-50 text-emerald-700 ring-emerald-200",
    red: "bg-rose-50 text-rose-700 ring-rose-200",
    amber: "bg-amber-50 text-amber-700 ring-amber-200",
    gray: "bg-slate-100 text-slate-600 ring-slate-200",
  };
  return (
    <span className={`inline-flex items-center rounded-full px-2.5 py-0.5 text-xs font-semibold ring-1 ${styles[color]}`}>
      {children}
    </span>
  );
};

// ─────────────────────────────────────────────────────────────────────────────
const ReportsPage: React.FC = () => {
  const { settings } = useSettings();
  const [tab, setTab] = useState<Tab>("overview");
  const [range, setRange] = useState<{ start: string; end: string }>({
    start: formatDate(new Date(Date.now() - 29 * 24 * 60 * 60 * 1000)),
    end: formatDate(new Date()),
  });

  const fmt = (v: number) => formatCurrency(v, settings);

  // Data
  const { data: daily, isLoading: l1, refetch: r1 } = useDailySalesReport(range.end);
  const { data: salesRange, isLoading: l2, refetch: r2 } = useSalesRangeReport(range.start, range.end);
  const { data: employeePerf, isLoading: l3, refetch: r3 } = useEmployeePerformanceReport(range.start, range.end);
  const { data: productPerf, isLoading: l4, refetch: r4 } = useProductPerformanceReport(range.start, range.end, 10);
  const { data: inventory, isLoading: l5, refetch: r5 } = useInventoryReport();
  const isLoading = l1 || l2 || l3 || l4 || l5;
  const refetchAll = () => { r1(); r2(); r3(); r4(); r5(); };

  // Chart data
  const paymentData = (daily?.salesByPaymentMethod ?? []).map((pm: any) => ({
    name: pm.paymentMethod,
    amount: pm._sum?.finalAmount ?? 0,
    count: pm._count?.id ?? 0,
  }));

  const productChartData = (productPerf?.products ?? []).slice(0, 7).map((p: any) => ({
    name: p.product?.name?.length > 16 ? p.product.name.slice(0, 16) + "…" : p.product?.name,
    revenue: p.totalRevenue,
    units: p.totalQuantitySold,
    profit: p.estimatedProfit,
  }));

  const empChartData = (employeePerf?.performance ?? []).map((e: any) => ({
    name: e.employee?.name?.split(" ")[0],
    sales: e.totalSales,
    transactions: e.totalTransactions,
  }));

  const totalEmpSales = empChartData.reduce((s: number, e: any) => s + e.sales, 0);

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 via-indigo-50/20 to-white">
      <div className="container mx-auto px-4 py-8 sm:px-6 lg:px-8">

        {/* ── Page Header ── */}
        <div className="mb-8">
          <div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between">
            <div>
              <div className="flex items-center gap-3">
                <div className="flex h-10 w-10 items-center justify-center rounded-2xl bg-gradient-to-br from-indigo-500 to-violet-600 shadow-lg shadow-indigo-200">
                  <svg className="h-5 w-5 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z" />
                  </svg>
                </div>
                <div>
                  <h1 className="bg-gradient-to-r from-indigo-600 via-violet-600 to-purple-600 bg-clip-text text-3xl font-extrabold tracking-tight text-transparent">
                    Reports & Analytics
                  </h1>
                  <p className="mt-0.5 text-sm text-slate-500">Comprehensive performance insights for your store</p>
                </div>
              </div>
            </div>

            {/* Controls */}
            <div className="flex flex-wrap items-center gap-2">
              <div className="flex items-center overflow-hidden rounded-xl border border-gray-200 bg-white shadow-sm">
                <span className="border-r border-gray-200 px-3 py-2 text-xs font-bold uppercase text-gray-400">From</span>
                <input
                  type="date" value={range.start}
                  onChange={e => setRange(r => ({ ...r, start: e.target.value }))}
                  className="border-none px-3 py-2 text-sm font-semibold text-gray-700 outline-none"
                />
              </div>
              <div className="flex items-center overflow-hidden rounded-xl border border-gray-200 bg-white shadow-sm">
                <span className="border-r border-gray-200 px-3 py-2 text-xs font-bold uppercase text-gray-400">To</span>
                <input
                  type="date" value={range.end}
                  onChange={e => setRange(r => ({ ...r, end: e.target.value }))}
                  className="border-none px-3 py-2 text-sm font-semibold text-gray-700 outline-none"
                />
              </div>
              <button
                onClick={refetchAll}
                disabled={isLoading}
                className="flex items-center gap-1.5 rounded-xl border border-gray-200 bg-white px-3 py-2 text-sm font-semibold text-gray-600 shadow-sm transition-all hover:bg-indigo-50 hover:text-indigo-700 disabled:opacity-50"
              >
                <svg className={`h-4 w-4 ${isLoading ? "animate-spin" : ""}`} fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15" />
                </svg>
                Refresh
              </button>
            </div>
          </div>
        </div>

        {/* ── Tab Bar ── */}
        <div className="mb-6 flex overflow-x-auto">
          <div className="flex gap-1 rounded-2xl border border-gray-200 bg-white p-1.5 shadow-sm">
            {TABS.map(t => (
              <button
                key={t.id}
                onClick={() => setTab(t.id)}
                className={`flex items-center gap-2 rounded-xl px-4 py-2 text-sm font-semibold transition-all duration-200 whitespace-nowrap ${
                  tab === t.id
                    ? "bg-gradient-to-r from-indigo-600 to-violet-600 text-white shadow-md shadow-indigo-200"
                    : "text-gray-500 hover:bg-gray-100 hover:text-gray-800"
                }`}
              >
                {t.icon}
                {t.label}
              </button>
            ))}
          </div>
        </div>

        {/* ── Content ── */}
        {isLoading ? <Skeleton /> : (
          <div className="space-y-6">

            {/* ══════════════════ OVERVIEW ══════════════════ */}
            {tab === "overview" && (
              <>
                {/* Today row */}
                <div>
                  <div className="mb-3 flex items-center gap-2">
                    <div className="h-4 w-1 rounded-full bg-indigo-500" />
                    <p className="text-sm font-bold text-gray-700">Today — {daily?.date ?? "—"}</p>
                  </div>
                  <div className="grid grid-cols-2 gap-4 sm:grid-cols-4">
                    <StatCard label="Revenue" value={fmt(daily?.summary?.totalSales ?? 0)} gradient="bg-gradient-to-br from-indigo-500 via-indigo-600 to-blue-600"
                      icon={<svg className="h-4 w-4 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 8c-1.657 0-3 .895-3 2s1.343 2 3 2 3 .895 3 2-1.343 2-3 2m0-8c1.11 0 2.08.402 2.599 1M12 8V7m0 1v8m0 0v1m0-1c-1.11 0-2.08-.402-2.599-1M21 12a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>}
                    />
                    <StatCard label="Transactions" value={daily?.summary?.totalTransactions ?? 0} gradient="bg-gradient-to-br from-emerald-500 via-emerald-600 to-teal-600"
                      icon={<svg className="h-4 w-4 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 3h2l.4 2M7 13h10l4-8H5.4M7 13L5.4 5M7 13l-2.293 2.293c-.63.63-.184 1.707.707 1.707H17m0 0a2 2 0 100 4 2 2 0 000-4zm-8 2a2 2 0 11-4 0 2 2 0 014 0z" /></svg>}
                    />
                    <StatCard label="Tax Collected" value={fmt(daily?.summary?.totalTax ?? 0)} gradient="bg-gradient-to-br from-amber-500 via-amber-600 to-orange-600"
                      icon={<svg className="h-4 w-4 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 7h6m0 10v-3m-3 3h.01M9 17h.01M9 14h.01M12 14h.01M15 11h.01M12 11h.01M9 11h.01M7 21h10a2 2 0 002-2V5a2 2 0 00-2-2H7a2 2 0 00-2 2v14a2 2 0 002 2z" /></svg>}
                    />
                    <StatCard label="Discounts" value={fmt(daily?.summary?.totalDiscount ?? 0)} gradient="bg-gradient-to-br from-rose-500 via-rose-600 to-pink-600"
                      icon={<svg className="h-4 w-4 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M7 7h.01M7 3h5c.512 0 1.024.195 1.414.586l7 7a2 2 0 010 2.828l-7 7a2 2 0 01-2.828 0l-7-7A1.994 1.994 0 013 12V7a4 4 0 014-4z" /></svg>}
                    />
                  </div>
                </div>

                {/* Period summary */}
                <div>
                  <div className="mb-3 flex items-center gap-2">
                    <div className="h-4 w-1 rounded-full bg-violet-500" />
                    <p className="text-sm font-bold text-gray-700">Period: {range.start} → {range.end}</p>
                  </div>
                  <div className="grid grid-cols-2 gap-4 sm:grid-cols-4">
                    <StatCard label="Period Revenue" value={fmt(salesRange?.summary?.totalSales ?? 0)} gradient="bg-gradient-to-br from-violet-500 via-violet-600 to-purple-700"
                      icon={<svg className="h-4 w-4 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 7h8m0 0v8m0-8l-8 8-4-4-6 6" /></svg>}
                    />
                    <StatCard label="Transactions" value={salesRange?.summary?.totalTransactions ?? 0} gradient="bg-gradient-to-br from-sky-500 via-sky-600 to-cyan-600"
                      icon={<svg className="h-4 w-4 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2" /></svg>}
                    />
                    <StatCard label="Tax Collected" value={fmt(salesRange?.summary?.totalTax ?? 0)} gradient="bg-gradient-to-br from-amber-500 via-orange-500 to-orange-600"
                      icon={<svg className="h-4 w-4 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17 9V7a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2m2 4h10a2 2 0 002-2v-6a2 2 0 00-2-2H9a2 2 0 00-2 2v6a2 2 0 002 2zm7-5a2 2 0 11-4 0 2 2 0 014 0z" /></svg>}
                    />
                    <StatCard label="Avg. Order Value" value={fmt(salesRange?.summary?.totalTransactions ? (salesRange.summary.totalSales / salesRange.summary.totalTransactions) : 0)} gradient="bg-gradient-to-br from-teal-500 via-teal-600 to-emerald-600"
                      icon={<svg className="h-4 w-4 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z" /></svg>}
                    />
                  </div>
                </div>

                {/* Two column: Payment chart + table */}
                {paymentData.length > 0 && (
                  <div className="grid grid-cols-1 gap-6 lg:grid-cols-2">
                    {/* Pie Chart */}
                    <Card className="p-6">
                      <SectionHeader title="Payment Method Split" sub="By number of transactions" />
                      <ResponsiveContainer width="100%" height={240} className="mt-4">
                        <PieChart>
                          <Pie data={paymentData} cx="50%" cy="50%" innerRadius={60} outerRadius={90} dataKey="count" nameKey="name" paddingAngle={3}>
                            {paymentData.map((_: any, i: number) => <Cell key={i} fill={PALETTE[i % PALETTE.length]} />)}
                          </Pie>
                          <Tooltip content={<ChartTooltip formatter={(v: any) => `${v} txns`} />} />
                          <Legend formatter={(v) => <span className="text-xs font-semibold text-gray-600">{v}</span>} />
                        </PieChart>
                      </ResponsiveContainer>
                    </Card>

                    {/* Revenue table */}
                    <Card className="overflow-hidden">
                      <div className="border-b border-gray-100 p-5">
                        <SectionHeader
                          title="Revenue by Payment Method"
                          onPrint={() => printTable(
                            "Payment Method Revenue",
                            `Period: ${range.start} to ${range.end}`,
                            ["Method", "Revenue", "Transactions"],
                            paymentData.map((p: any) => [p.name, fmt(p.amount), p.count])
                          )}
                        />
                      </div>
                      <div className="divide-y divide-gray-50">
                        {paymentData.map((pm: any, i: number) => (
                          <div key={i} className="flex items-center justify-between px-5 py-3.5 transition-colors hover:bg-gray-50">
                            <div className="flex items-center gap-3">
                              <div className="h-3 w-3 rounded-full" style={{ background: PALETTE[i % PALETTE.length] }} />
                              <span className="text-sm font-semibold text-gray-800">{pm.name}</span>
                            </div>
                            <div className="text-right">
                              <p className="text-sm font-bold text-gray-900">{fmt(pm.amount)}</p>
                              <p className="text-xs text-gray-400">{pm.count} txns</p>
                            </div>
                          </div>
                        ))}
                      </div>
                    </Card>
                  </div>
                )}

                {/* Transactions Table */}
                <Card className="overflow-hidden">
                  <div className="border-b border-gray-100 p-5">
                    <SectionHeader
                      title="Recent Transactions"
                      sub={`${(salesRange?.sales ?? []).length} transactions in period`}
                      onPrint={() => printTable(
                        "Sales History", `Period: ${range.start} to ${range.end}`,
                        ["Receipt", "Customer", "Date", "Method", "Amount"],
                        (salesRange?.sales ?? []).slice(0, 50).map((s: any) => [
                          s.receiptId, s.customer?.name ?? "Walk-in",
                          new Date(s.createdAt).toLocaleString(),
                          s.paymentMethod ?? "—",
                          fmt(s.finalAmount),
                        ])
                      )}
                    />
                  </div>
                  <div className="overflow-x-auto">
                    <table className="w-full text-sm">
                      <thead>
                        <tr className="border-b border-gray-100 bg-gray-50/60">
                          <th className="px-5 py-3 text-left text-xs font-bold uppercase tracking-wider text-gray-400">Receipt</th>
                          <th className="px-5 py-3 text-left text-xs font-bold uppercase tracking-wider text-gray-400">Customer</th>
                          <th className="px-5 py-3 text-left text-xs font-bold uppercase tracking-wider text-gray-400">Date & Time</th>
                          <th className="px-5 py-3 text-left text-xs font-bold uppercase tracking-wider text-gray-400">Method</th>
                          <th className="px-5 py-3 text-right text-xs font-bold uppercase tracking-wider text-gray-400">Amount</th>
                        </tr>
                      </thead>
                      <tbody className="divide-y divide-gray-50">
                        {(salesRange?.sales ?? []).length === 0 ? (
                          <tr><td colSpan={5} className="py-16 text-center">
                            <div className="flex flex-col items-center gap-2">
                              <svg className="h-10 w-10 text-gray-200" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1} d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2" /></svg>
                              <p className="text-sm font-medium text-gray-400">No transactions in this period</p>
                            </div>
                          </td></tr>
                        ) : (salesRange?.sales ?? []).slice(0, 25).map((s: any) => (
                          <tr key={s.id} className="transition-colors hover:bg-indigo-50/30">
                            <td className="px-5 py-3 font-mono text-xs font-semibold text-indigo-600">{s.receiptId}</td>
                            <td className="px-5 py-3 text-gray-700">{s.customer?.name ?? <span className="italic text-gray-400">Walk-in</span>}</td>
                            <td className="px-5 py-3 text-xs text-gray-400">{new Date(s.createdAt).toLocaleString()}</td>
                            <td className="px-5 py-3"><Badge color="gray">{s.paymentMethod ?? "—"}</Badge></td>
                            <td className="px-5 py-3 text-right font-bold text-gray-900">{fmt(s.finalAmount)}</td>
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  </div>
                </Card>
              </>
            )}

            {/* ══════════════════ PRODUCTS ══════════════════ */}
            {tab === "products" && (
              <>
                <div className="grid grid-cols-2 gap-4 sm:grid-cols-4">
                  <StatCard label="Items Tracked" value={productPerf?.products?.length ?? 0} gradient="bg-gradient-to-br from-indigo-500 to-blue-600"
                    icon={<svg className="h-4 w-4 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M20 7l-8-4-8 4m16 0l-8 4m8-4v10l-8 4m0-10L4 7m8 4v10M4 7v10l8 4" /></svg>}
                  />
                  <StatCard label="Units Sold" value={(productPerf?.products ?? []).reduce((s: number, p: any) => s + p.totalQuantitySold, 0).toLocaleString()} gradient="bg-gradient-to-br from-emerald-500 to-teal-600"
                    icon={<svg className="h-4 w-4 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M16 11V7a4 4 0 00-8 0v4M5 9h14l1 12H4L5 9z" /></svg>}
                  />
                  <StatCard label="Total Revenue" value={fmt((productPerf?.products ?? []).reduce((s: number, p: any) => s + p.totalRevenue, 0))} gradient="bg-gradient-to-br from-violet-500 to-purple-700"
                    icon={<svg className="h-4 w-4 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 8c-1.657 0-3 .895-3 2s1.343 2 3 2 3 .895 3 2-1.343 2-3 2m0-8c1.11 0 2.08.402 2.599 1M12 8V7m0 1v8m0 0v1m0-1c-1.11 0-2.08-.402-2.599-1M21 12a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>}
                  />
                  <StatCard label="Est. Profit" value={fmt((productPerf?.products ?? []).reduce((s: number, p: any) => s + p.estimatedProfit, 0))} gradient="bg-gradient-to-br from-amber-500 to-orange-600"
                    icon={<svg className="h-4 w-4 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 7h8m0 0v8m0-8l-8 8-4-4-6 6" /></svg>}
                  />
                </div>

                {productChartData.length > 0 && (
                  <Card className="p-6">
                    <SectionHeader title="Top Products by Revenue" sub="Showing top 7 products" />
                    <ResponsiveContainer width="100%" height={280} className="mt-4">
                      <BarChart data={productChartData} layout="vertical" barSize={16} margin={{ left: 10 }}>
                        <CartesianGrid strokeDasharray="3 3" stroke="#f1f5f9" horizontal={false} />
                        <XAxis type="number" tick={{ fontSize: 11, fill: "#94a3b8" }} tickFormatter={fmt} width={80} />
                        <YAxis type="category" dataKey="name" tick={{ fontSize: 12, fill: "#475569", fontWeight: 600 }} width={130} />
                        <Tooltip content={<ChartTooltip formatter={fmt} />} />
                        <Bar dataKey="revenue" name="Revenue" radius={[0, 8, 8, 0]}>
                          {productChartData.map((_: any, i: number) => <Cell key={i} fill={PALETTE[i % PALETTE.length]} />)}
                        </Bar>
                      </BarChart>
                    </ResponsiveContainer>
                  </Card>
                )}

                <Card className="overflow-hidden">
                  <div className="border-b border-gray-100 p-5">
                    <SectionHeader title="Product Performance Table"
                      onPrint={() => printTable(
                        "Product Performance", `Period: ${range.start} to ${range.end}`,
                        ["#", "Product", "Units Sold", "Revenue", "Transactions", "Est. Profit"],
                        (productPerf?.products ?? []).map((p: any, i: number) => [i + 1, p.product?.name, p.totalQuantitySold, fmt(p.totalRevenue), p.totalTransactions, fmt(p.estimatedProfit)])
                      )}
                    />
                  </div>
                  <div className="overflow-x-auto">
                    <table className="w-full text-sm">
                      <thead>
                        <tr className="border-b border-gray-100 bg-gray-50/60">
                          <th className="px-5 py-3 text-left text-xs font-bold uppercase tracking-wider text-gray-400">#</th>
                          <th className="px-5 py-3 text-left text-xs font-bold uppercase tracking-wider text-gray-400">Product</th>
                          <th className="px-5 py-3 text-right text-xs font-bold uppercase tracking-wider text-gray-400">Units</th>
                          <th className="px-5 py-3 text-right text-xs font-bold uppercase tracking-wider text-gray-400">Revenue</th>
                          <th className="px-5 py-3 text-right text-xs font-bold uppercase tracking-wider text-gray-400">Txns</th>
                          <th className="px-5 py-3 text-right text-xs font-bold uppercase tracking-wider text-gray-400">Est. Profit</th>
                        </tr>
                      </thead>
                      <tbody className="divide-y divide-gray-50">
                        {(productPerf?.products ?? []).length === 0 ? (
                          <tr><td colSpan={6} className="py-12 text-center text-sm text-gray-400">No product data for this period.</td></tr>
                        ) : (productPerf?.products ?? []).map((p: any, i: number) => (
                          <tr key={i} className="transition-colors hover:bg-violet-50/30">
                            <td className="px-5 py-3.5">
                              <span className="flex h-6 w-6 items-center justify-center rounded-full bg-gray-100 text-xs font-bold text-gray-500">{i + 1}</span>
                            </td>
                            <td className="px-5 py-3.5 font-semibold text-gray-900">{p.product?.name}</td>
                            <td className="px-5 py-3.5 text-right text-gray-600">{p.totalQuantitySold.toLocaleString()}</td>
                            <td className="px-5 py-3.5 text-right font-bold text-indigo-600">{fmt(p.totalRevenue)}</td>
                            <td className="px-5 py-3.5 text-right text-gray-500">{p.totalTransactions}</td>
                            <td className="px-5 py-3.5 text-right font-semibold text-emerald-600">{fmt(p.estimatedProfit)}</td>
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  </div>
                </Card>
              </>
            )}

            {/* ══════════════════ EMPLOYEES ══════════════════ */}
            {tab === "employees" && (
              <>
                <div className="grid grid-cols-2 gap-4 sm:grid-cols-3">
                  <StatCard label="Staff Tracked" value={employeePerf?.performance?.length ?? 0} gradient="bg-gradient-to-br from-indigo-500 to-blue-600"
                    icon={<svg className="h-4 w-4 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z" /></svg>}
                  />
                  <StatCard label="Total Revenue" value={fmt(totalEmpSales)} gradient="bg-gradient-to-br from-emerald-500 to-teal-600"
                    icon={<svg className="h-4 w-4 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 8c-1.657 0-3 .895-3 2s1.343 2 3 2 3 .895 3 2-1.343 2-3 2m0-8c1.11 0 2.08.402 2.599 1M12 8V7m0 1v8m0 0v1m0-1c-1.11 0-2.08-.402-2.599-1M21 12a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>}
                  />
                  <StatCard label="Total Transactions" value={(employeePerf?.performance ?? []).reduce((s: number, e: any) => s + e.totalTransactions, 0).toLocaleString()} gradient="bg-gradient-to-br from-violet-500 to-purple-700"
                    icon={<svg className="h-4 w-4 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2" /></svg>}
                  />
                </div>

                {empChartData.length > 0 && (
                  <Card className="p-6">
                    <SectionHeader title="Revenue by Employee" />
                    <ResponsiveContainer width="100%" height={240} className="mt-4">
                      <BarChart data={empChartData} barSize={40}>
                        <CartesianGrid strokeDasharray="3 3" stroke="#f1f5f9" />
                        <XAxis dataKey="name" tick={{ fontSize: 12, fill: "#475569", fontWeight: 600 }} />
                        <YAxis tick={{ fontSize: 11, fill: "#94a3b8" }} tickFormatter={fmt} width={85} />
                        <Tooltip content={<ChartTooltip formatter={fmt} />} />
                        <Bar dataKey="sales" name="Revenue" radius={[8, 8, 0, 0]}>
                          {empChartData.map((_: any, i: number) => <Cell key={i} fill={PALETTE[i % PALETTE.length]} />)}
                        </Bar>
                      </BarChart>
                    </ResponsiveContainer>
                  </Card>
                )}

                <Card className="overflow-hidden">
                  <div className="border-b border-gray-100 p-5">
                    <SectionHeader title="Employee Performance Detail"
                      onPrint={() => printTable(
                        "Employee Performance", `Period: ${range.start} to ${range.end}`,
                        ["Employee", "Total Sales", "Transactions", "Avg. per Sale", "Share"],
                        (employeePerf?.performance ?? []).map((e: any) => [
                          e.employee?.name, fmt(e.totalSales), e.totalTransactions,
                          fmt(e.averageTransaction),
                          totalEmpSales > 0 ? ((e.totalSales / totalEmpSales) * 100).toFixed(1) + "%" : "0%",
                        ])
                      )}
                    />
                  </div>
                  <div className="overflow-x-auto">
                    <table className="w-full text-sm">
                      <thead>
                        <tr className="border-b border-gray-100 bg-gray-50/60">
                          <th className="px-5 py-3 text-left text-xs font-bold uppercase tracking-wider text-gray-400">Employee</th>
                          <th className="px-5 py-3 text-right text-xs font-bold uppercase tracking-wider text-gray-400">Total Sales</th>
                          <th className="px-5 py-3 text-right text-xs font-bold uppercase tracking-wider text-gray-400">Transactions</th>
                          <th className="px-5 py-3 text-right text-xs font-bold uppercase tracking-wider text-gray-400">Avg. per Sale</th>
                          <th className="px-5 py-3 text-right text-xs font-bold uppercase tracking-wider text-gray-400">Share</th>
                        </tr>
                      </thead>
                      <tbody className="divide-y divide-gray-50">
                        {(employeePerf?.performance ?? []).length === 0 ? (
                          <tr><td colSpan={5} className="py-12 text-center text-sm text-gray-400">No employee data for this period.</td></tr>
                        ) : (employeePerf?.performance ?? []).map((emp: any, i: number) => {
                          const share = totalEmpSales > 0 ? ((emp.totalSales / totalEmpSales) * 100) : 0;
                          return (
                            <tr key={i} className="transition-colors hover:bg-blue-50/30">
                              <td className="px-5 py-3.5">
                                <div className="flex items-center gap-3">
                                  <div className="flex h-8 w-8 items-center justify-center rounded-full text-sm font-extrabold text-white shadow-sm" style={{ background: PALETTE[i % PALETTE.length] }}>
                                    {emp.employee?.name?.charAt(0)?.toUpperCase() ?? "?"}
                                  </div>
                                  <span className="font-semibold text-gray-900">{emp.employee?.name}</span>
                                </div>
                              </td>
                              <td className="px-5 py-3.5 text-right font-bold text-gray-900">{fmt(emp.totalSales)}</td>
                              <td className="px-5 py-3.5 text-right text-gray-600">{emp.totalTransactions}</td>
                              <td className="px-5 py-3.5 text-right text-gray-600">{fmt(emp.averageTransaction)}</td>
                              <td className="px-5 py-3.5 text-right">
                                <div className="flex items-center justify-end gap-2">
                                  <div className="h-1.5 w-24 overflow-hidden rounded-full bg-gray-100">
                                    <div className="h-full rounded-full transition-all" style={{ width: `${share}%`, background: PALETTE[i % PALETTE.length] }} />
                                  </div>
                                  <span className="w-10 text-right text-xs font-bold text-gray-500">{share.toFixed(1)}%</span>
                                </div>
                              </td>
                            </tr>
                          );
                        })}
                      </tbody>
                    </table>
                  </div>
                </Card>
              </>
            )}

            {/* ══════════════════ INVENTORY ══════════════════ */}
            {tab === "inventory" && (
              <>
                <div className="grid grid-cols-2 gap-4 sm:grid-cols-4">
                  <StatCard label="Total Products" value={inventory?.totalProducts ?? 0} gradient="bg-gradient-to-br from-indigo-500 to-blue-600"
                    icon={<svg className="h-4 w-4 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 8h14M5 8a2 2 0 110-4h14a2 2 0 110 4M5 8v10a2 2 0 002 2h10a2 2 0 002-2V8m-9 4h4" /></svg>}
                  />
                  <StatCard label="Stock Value" value={fmt(inventory?.totalInventoryValue ?? 0)} gradient="bg-gradient-to-br from-emerald-500 to-teal-600"
                    icon={<svg className="h-4 w-4 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 8c-1.657 0-3 .895-3 2s1.343 2 3 2 3 .895 3 2-1.343 2-3 2m0-8c1.11 0 2.08.402 2.599 1M12 8V7m0 1v8m0 0v1m0-1c-1.11 0-2.08-.402-2.599-1M21 12a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>}
                  />
                  <StatCard label="Out of Stock" value={inventory?.outOfStockCount ?? 0} gradient="bg-gradient-to-br from-rose-500 to-red-600"
                    icon={<svg className="h-4 w-4 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" /></svg>}
                  />
                  <StatCard label="Low Stock Alert" value={inventory?.lowStockCount ?? 0} gradient="bg-gradient-to-br from-amber-500 to-orange-600"
                    icon={<svg className="h-4 w-4 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" /></svg>}
                  />
                </div>

                {/* Alert banners */}
                {(inventory?.outOfStockItems ?? []).length > 0 && (
                  <div className="rounded-2xl border border-red-200 bg-gradient-to-r from-red-50 to-rose-50 p-5">
                    <div className="mb-3 flex items-center gap-2">
                      <div className="flex h-7 w-7 items-center justify-center rounded-full bg-red-100">
                        <svg className="h-4 w-4 text-red-600" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" /></svg>
                      </div>
                      <h3 className="font-bold text-red-800">Out of Stock — {inventory?.outOfStockItems?.length} items</h3>
                    </div>
                    <div className="flex flex-wrap gap-2">
                      {(inventory?.outOfStockItems ?? []).map((p: any, i: number) => (
                        <span key={i} className="rounded-full border border-red-200 bg-white px-3 py-1 text-xs font-semibold text-red-700">{p.name}</span>
                      ))}
                    </div>
                  </div>
                )}

                {(inventory?.lowStockItems ?? []).length > 0 && (
                  <div className="rounded-2xl border border-amber-200 bg-gradient-to-r from-amber-50 to-yellow-50 p-5">
                    <div className="mb-3 flex items-center gap-2">
                      <div className="flex h-7 w-7 items-center justify-center rounded-full bg-amber-100">
                        <svg className="h-4 w-4 text-amber-600" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" /></svg>
                      </div>
                      <h3 className="font-bold text-amber-800">Low Stock Warning — {inventory?.lowStockItems?.length} items</h3>
                    </div>
                    <div className="flex flex-wrap gap-2">
                      {(inventory?.lowStockItems ?? []).map((p: any, i: number) => (
                        <span key={i} className="rounded-full border border-amber-200 bg-white px-3 py-1 text-xs font-semibold text-amber-700">
                          {p.name} ({p.stock ?? p.stockQuantity ?? 0} left)
                        </span>
                      ))}
                    </div>
                  </div>
                )}

                <Card className="overflow-hidden">
                  <div className="border-b border-gray-100 p-5">
                    <SectionHeader title="Full Inventory List"
                      sub={`${(inventory?.products ?? []).length} products`}
                      onPrint={() => printTable(
                        "Inventory Report", `Generated ${new Date().toLocaleString()}`,
                        ["Product", "SKU", "Cost", "Price", "In Stock", "Value", "Status"],
                        (inventory?.products ?? []).map((p: any) => {
                          const qty = p.stock ?? p.stockQuantity ?? 0;
                          return [p.name, p.sku ?? "—", fmt(p.costPrice ?? 0), fmt(p.price ?? 0), qty, fmt(qty * (p.costPrice ?? 0)), qty <= 0 ? "Out of Stock" : qty <= 5 ? "Low" : "OK"];
                        })
                      )}
                    />
                  </div>
                  <div className="overflow-x-auto">
                    <table className="w-full text-sm">
                      <thead>
                        <tr className="border-b border-gray-100 bg-gray-50/60">
                          <th className="px-5 py-3 text-left text-xs font-bold uppercase tracking-wider text-gray-400">Product</th>
                          <th className="px-5 py-3 text-left text-xs font-bold uppercase tracking-wider text-gray-400">SKU</th>
                          <th className="px-5 py-3 text-right text-xs font-bold uppercase tracking-wider text-gray-400">Cost</th>
                          <th className="px-5 py-3 text-right text-xs font-bold uppercase tracking-wider text-gray-400">Price</th>
                          <th className="px-5 py-3 text-right text-xs font-bold uppercase tracking-wider text-gray-400">In Stock</th>
                          <th className="px-5 py-3 text-right text-xs font-bold uppercase tracking-wider text-gray-400">Value</th>
                          <th className="px-5 py-3 text-center text-xs font-bold uppercase tracking-wider text-gray-400">Status</th>
                        </tr>
                      </thead>
                      <tbody className="divide-y divide-gray-50">
                        {(inventory?.products ?? []).length === 0 ? (
                          <tr><td colSpan={7} className="py-12 text-center text-sm text-gray-400">No inventory data.</td></tr>
                        ) : (inventory?.products ?? []).map((p: any, i: number) => {
                          const qty = p.stock ?? p.stockQuantity ?? 0;
                          const isOut = qty <= 0;
                          const isLow = !isOut && qty <= (p.lowStockThreshold ?? 5);
                          return (
                            <tr key={i} className="transition-colors hover:bg-blue-50/20">
                              <td className="px-5 py-3.5 font-semibold text-gray-900">{p.name}</td>
                              <td className="px-5 py-3.5 font-mono text-xs text-gray-400">{p.sku ?? "—"}</td>
                              <td className="px-5 py-3.5 text-right text-gray-500">{fmt(p.costPrice ?? 0)}</td>
                              <td className="px-5 py-3.5 text-right text-gray-600">{fmt(p.price ?? 0)}</td>
                              <td className={`px-5 py-3.5 text-right font-bold ${isOut ? "text-red-600" : isLow ? "text-amber-600" : "text-gray-900"}`}>{qty}</td>
                              <td className="px-5 py-3.5 text-right font-semibold text-indigo-600">{fmt(qty * (p.costPrice ?? 0))}</td>
                              <td className="px-5 py-3.5 text-center">
                                {isOut ? <Badge color="red">Out of Stock</Badge> : isLow ? <Badge color="amber">Low Stock</Badge> : <Badge color="green">In Stock</Badge>}
                              </td>
                            </tr>
                          );
                        })}
                      </tbody>
                    </table>
                  </div>
                </Card>
              </>
            )}

          </div>
        )}
      </div>
    </div>
  );
};

export default ReportsPage;
